//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FOX Password Safe.rc
//
#define IDB_UNENCRYPT                   3
#define IDI_LOGO1                       7
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDS_BLANK_DOC_INTRO             129
#define IDD_LOAD_DATABASE               130
#define IDD_NEW_DATABASE                134
#define IDD_ENTER_NEW_PASSWORD          135
#define IDD_ENTER_NEW_CATEGORY          136
#define IDB_LOGO1                       139
#define IDD_TOOLBAR_DLG                 153
#define IDD_BACKUP                      154
#define IDD_RESTORE                     155
#define IDI_ICON1                       179
#define IDB_IMAGELIST2                  193
#define IDD_CHOOSE_ITEMS_TO_PRINT       196
#define IDD_CHANGE_PASSWORD_DLG         197
#define IDD_CHOOSE_SELECT_PRINT_ITEMS   198
#define IDR_MENU_TRAY                   200
#define IDD_WARNING_DLG                 201
#define IDD_PASSWORD_POPUP              202
#define IDD_EXPIRED_PASSWORD_DLG        203
#define IDD_DIALOG_OPTIONS              204
#define IDD_ENTER_REG_CODE              205
#define IDD_NAG_DLG                     206
#define IDD_ENTER_NEW_CREDIT_CARD       207
#define IDD_DIALOG1                     208
#define IDD_CHOOSE_NEW_ENTRY_TYPE       208
#define IDD_ASK_CLOSE_OR_HIDE_TO_TRAY   217
#define IDB_FILEOPENUP                  218
#define IDD_ENTER_NEW_ENCRYPTED_FILE    218
#define IDB_FILEOPENDOWN                219
#define IDB_FILE_FIND1                  220
#define IDB_FILE_FIND2                  221
#define IDB_FILE_DELETE1                222
#define IDB_FILE_DELETE2                224
#define IDB_FILE_PRINT1                 225
#define IDB_FILE_PRINT2                 226
#define IDB_FILE_CLIPNAME1              227
#define IDB_FILE_CLIPNAME2              228
#define IDB_FILE_CLIPPASS1              229
#define IDB_FILE_CLIPPASS2              230
#define IDB_FILE_INFO1                  231
#define IDB_FILE_INFO2                  232
#define IDB_FILE_EMPTY1                 234
#define IDB_FILE_EMPTY2                 235
#define IDB_FILE_NEW1                   236
#define IDB_FILE_NEW2                   237
#define IDB_FILE_EDIT1                  238
#define IDB_FILE_EDIT2                  239
#define IDB_FILE_LOADSITE1              240
#define IDB_FILE_LOADSITE2              241
#define IDB_CLIP_DOWN                   242
#define IDB_CLIP_UP                     243
#define IDB_GLOBE_UP                    244
#define IDB_GLOBE_DOWN                  245
#define IDB_SHOWPASS1                   246
#define IDB_BITMAP1                     247
#define IDB_SHOWPASS2                   247
#define IDB_FILE_SEARCHBAR1             249
#define IDB_FILE_SEARCHBAR2             250
#define IDB_FILE_SHOWALL1               251
#define IDB_FILE_SHOWALL2               252
#define IDI_ICON2                       255
#define IDB_ICON_CC                     256
#define IDB_ICON_USERNAME               257
#define IDB_ICON_FOLDER                 258
#define IDB_BUT_DONE1                   259
#define IDB_BUT_DONE2                   260
#define IDB_BUT_COPY1                   261
#define IDB_BUT_COPY2                   262
#define IDB_BUT_SHOW1                   263
#define IDB_BUT_SHOW2                   264
#define IDB_BUT_LOADSITE1               265
#define IDB_BUT_LOADSITE2               266
#define IDB_ICON_ENC_FILE               267
#define IDC_CURSOR_DRAG                 268
#define IDB_FILE_LOADFILE1              268
#define IDB_FILE_LOADFILE2              269
#define IDD_DIALOG_ECRYTPING_FILE       270
#define IDB_FILE_ENCRYPT2               270
#define IDB_FILE_ENCRYPT1               271
#define IDD_UNENCRYPT_FILE              275
#define IDC_FILE_PATH                   1000
#define IDC_BUTTON_BROWSE               1001
#define IDC_BUTTON_CREATE_NEW           1002
#define IDC_BUTTON_BROWSE2              1003
#define IDC_EDIT_PASSWORD               1004
#define IDC_NEW_FILE_PATH               1005
#define IDC_EDIT_PASSWORD_PREVIOUS      1006
#define IDC_BROWSE                      1007
#define IDC_PASSWORD                    1008
#define IDC_PASSWORD2                   1009
#define IDC_BROWSE2                     1009
#define IDC_COMBO_HEADING               1010
#define IDC_EDIT_DESC                   1011
#define IDC_EDIT_USERNAME               1012
#define IDC_EDIT_PASSWORD2              1013
#define IDC_EDIT_URL                    1014
#define IDC_EDIT_NOTES                  1015
#define IDC_DATETIMEPICKER1             1016
#define IDC_CHECK_NEVER_EXPIRES         1017
#define IDC_CHECK_USE_A_Z               1018
#define IDC_CHECK_USE_A_Z_LOWER         1019
#define IDC_CHECK_USE_0_9               1020
#define IDC_CHECK_USE_SPECIAL_CHARS     1021
#define IDC_EDIT_EXCLUDE_CHARS          1022
#define IDC_BUTTON_GENERATE_PASSWORD    1023
#define IDC_BUTTON_SHOW_PASSWORD        1024
#define IDC_EDIT_PASSWORD_LENGTH        1025
#define IDC_EDIT_NEW_NAME               1026
#define IDC_BUTTON_SHOW_PASSWORD_PREVIOUS 1027
#define ID_SHOW_HIDE_PASSWORD           1028
#define ID_SHOW_HIDE_PREVIOUS_PASSWORD  1029
#define IDC_NEW                         1030
#define IDC_OPEN                        1031
#define IDC_EDIT_PATH                   1032
#define IDC_LOAD_URL                    1033
#define IDC_EDIT_PATH2                  1034
#define IDC_COPY_USER_CLIP              1035
#define IDC_COPY_PASS_CLIP              1036
#define IDC_BUTTON_READ_LOCATION        1037
#define IDC_CLEAR_CLIP                  1038
#define IDC_RADIO_PRINT1                1039
#define IDC_RADIO_PRINT_ALL             1040
#define IDC_RADIO_PRINT_ALL_SEL         1041
#define IDC_CHECK_DESCRIPTION           1042
#define IDC_CHECK_USERNAME              1043
#define IDC_CHECK_PASSWORD              1044
#define IDC_CHECK_WEB_SITE              1045
#define IDC_CHECK_CATEGORY              1046
#define IDC_EDIT_CURRENT_PASS           1047
#define IDC_EDIT_NEW_PASS               1048
#define IDC_EDIT_REPEAT_PASS            1049
#define IDC_LIST_SELECT                 1050
#define IDC_CHECK_LOCK_BROWSER          1051
#define IDC_CHECK_DONT_SHOW_AGAIN       1052
#define IDC_STATIC_TEXT                 1053
#define IDC_CHECK_MASTER_PASS           1054
#define IDC_STATIC_DESCRIPTION          1055
#define IDC_EDIT_USERID                 1056
#define IDC_BUTTON_COPY_USER            1057
#define IDC_BUTTON_COPY_PASS            1058
#define IDC_BUTTON_SHOW_PASS            1059
#define IDC_BUTTON_LOAD_URL             1060
#define IDC_LIST1                       1061
#define IDC_BUTTON_UPDATE               1062
#define IDC_CHECK_AUTO_START            1063
#define IDC_CHECK_HIDE_IN_TRAY          1064
#define IDC_CHECK_HIDE_ONSTART          1065
#define IDC_CHECK_EMPTY_CLIP_ONCLOSE    1066
#define IDC_MYBUTTON_ID                 1067
#define IDC_LOAD_FILE                   1068
#define IDC_RADIO_EMPTY_PASS_IN_SYSTEM_TRAY 1072
#define IDC_RADIO_NO_EMPTY_PASS_ONMINIMIZE 1073
#define IDC_RADIO_EMPTY_PASS_AFTER_TIME_PERIOD 1074
#define IDC_EDIT_MINUTES_CLEAR_PASS     1075
#define IDC_CHECK_POPUP_PASS_DLG_ONLOAD_URL 1076
#define IDC_CHECK_HIDE_ONLOAD_URL       1077
#define IDC_RADIO_BROWSER_AUTO_UNLOCKDOWN 1078
#define IDC_EDIT_RESTORE_BROWER_TIME_MINS 1079
#define IDC_RADIO_MANUALLY_UNLOCK_DOWN_BROWSER 1080
#define IDC_CHECK_CLEAR_PASS_WHEN_SCREENSAVER_RUN 1081
#define IDC_EDIT_RESTORE_BROWER_TIME_SECS 1082
#define IDC_RADIO_PASS_NEVER_EXPIRES    1083
#define IDC_RADIO_PASS_EXPIRES_IN_DAYS  1084
#define IDC_EDIT_DEFAULT_DAYS_PASS_EXPIRES 1085
#define IDC_STATIC_REGISTERED_TO        1087
#define IDC_BUTTON_ENTER_REG_CODE       1088
#define IDC_BUTTON_ORDER_ONLINE         1089
#define IDC_EDIT_NAME                   1090
#define IDC_EDIT_COMPANY_NAME           1091
#define IDC_EDIT_REG_CODE               1092
#define IDC_TEXT_MSG                    1093
#define IDC_BUTTON_ORDER                1094
#define IDC_BUTTON_ENTER_CODE           1095
#define IDC_CREDIT_CARD_TYPE            1098
#define IDC_EDIT_CARD_NUMBER            1099
#define IDC_EDIT_NAME_ON_CARD           1101
#define IDC_EDIT_EXPIRE_DATE            1102
#define IDC_EDIT_CC_VERIFICATION_NUMBER 1103
#define IDC_EDIT_BANK_NAME              1104
#define IDC_EDIT_BILLING_NAME           1105
#define IDC_EDIT_BILLING_COMPANY        1106
#define IDC_EDIT_BILLING_ADDRESS1       1107
#define IDC_EDIT_BILLING_ADDRESS2       1108
#define IDC_EDIT_BILLING_CITY           1109
#define IDC_EDIT_BILLING_STATE          1110
#define IDC_EDIT_BILLING_POSTCODE       1111
#define IDC_EDIT_BILLING_COUNTRY        1112
#define IDC_EDIT_BILLING_EMAIL          1113
#define IDC_EDIT_BILLING_PHONE          1114
#define IDC_RADIO_PASSWORD              1115
#define IDC_RADIO_CREDIT_CARD           1116
#define IDC_CHECK_DEFAULT_CATEGORIES    1117
#define IDC_RADIO_NEW_CATEGORY          1117
#define IDC_RADIO_ENCRYPTED_FILE        1118
#define IDC_RADIO_HIDE_APP              1119
#define IDC_RADIO_CLOSE_APP             1120
#define IDC_CHECK1                      1121
#define IDC_EDIT_SEARCH                 1122
#define IDC_BUTTON_SEARCH               1123
#define IDC_BUTTON_SHOW_ALL             1124
#define IDC_EDIT_FILE_PATH              1125
#define IDC_CHECK_HIDE_FILENAME         1127
#define IDC_MSG                         1128
#define IDC_PROGRESS1                   1130
#define IDC_EDIT3                       1135
#define IDC_EDIT1                       1136
#define IDC_EDIT_MAX_LEN                1136
#define ID_FILE_ADDNEWENTRY             32772
#define ID_FILE_ADDNEWCATEGORY          32774
#define ID_EDIT_COPYPASSWORDTOCLIPBOARD 32785
#define ID_FILE_RESTOREDATABASE         32786
#define ID_FILE_BACKUP                  32787
#define ID_EDIT_EDITSELECTEDCATEGORY    32789
#define ID_EDIT_EDITSELECTEDENTRY       32790
#define ID_EDIT_DELETESELECTEDCATEGORY  32791
#define ID_EDIT_DELETESELECTEDENTRY     32792
#define ID_HELP_ONLINEHELPPAGE          32793
#define ID_LOADURL                      32797
#define ID_EDIT_EMPTYPASSWORDFROMCLIPBOARD 32798
#define ID_FILE_CHANGEDATABASEPASSWORD  32802
#define ID_MY_FILE_PRINT                32803
#define ID_TRAYMENU_EXIT                32804
#define ID_TRAYMENU_SHOWFOXPASSWORDSAFE 32805
#define ID_TRAYMENU_CREATENEWDATABASE   32807
#define ID_TRAYMENU_LOADWEBSITE         32813
#define ID_EDIT_LOCKDOWNWEBBROWSER      32820
#define ID_EDIT_RESTOREBROWSERTODEFAULT 32821
#define ID_SHOW_POPUP                   32822
#define ID_TOOLS_OPTIONS                32826
#define ID_HELP_REGISTERFOXPASSWORDSAFE 32829
#define ID_HELP_ENTERREGISTRATIONCODE   32830
#define ID_FIND_ITEM                    32831
#define ID_EDIT_ENCRYPTFILEENTRY        32832
#define ID_EDIT_UNENCRYPTFILEENTRY      32833
#define ID_Menu                         32834
#define ID_TOOLS_LOADSELECTEDENCRYPTEDFILE 32835
#define ID_TRAYMENU_ENCRYPTANYUNENCRYPTEDFILES 32836
#define ID_TOOLS_UNENCRYPTBACKEDUPFILE  32837
#define ID_TOOLS_EXPORTDATATOCSVFILE    32838
#define ID_BASE_MENU_UID                32900

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        276
#define _APS_NEXT_COMMAND_VALUE         32839
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
